version: '3.8'
services:
  backend:
    image: rain453/spring-app-image1:v1
    build: .
    ports:
      - target: 8000
        published: 8000
  frontend:
    image: rain453/frontend-react:v1
    build: .
    ports:
      - target: 80
        published: 80
  mysql:
    image: mysql:8
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cardatabase
    ports:
      - target: 3306
        published: 3306
    volumes:
      - cardatabase:/var/lib/mysql

volumes:
  cardatabase:
